const express =require('express');
const { signup, login, getAllUsers, getUserData } = require('../controller/Auth');
const { createCourse, getCoursedetails } = require('../controller/createCourse');
const { createSubject, getSubjectDetails } = require('../controller/createSubject');
const { createChapter, getAllChapters } = require('../controller/createChapter');
const { createTopic, getTotalTopics, getAllTopics } = require('../controller/createTopic');
const { createQuestionWithImage } = require('../controller/createQuestion');
const { getQuestionsForTest } = require('../controller/getQuestions');
const { createTest } = require('../controller/createTest');
const { submitTest } = require('../controller/submissionTest');
const { chatBot } = require('../controller/gemini');
const { updateProgress, getProgress, removeFromComplete } = require('../controller/completeProgrss');
const { sendBattleRequest } = require('../controller/createBattle');
const { generateQuestionPaper } = require('../controller/createQuestionPaper');
const { getSyllabus } = require('../controller/createSyllabus');
const {auth}=require('../middleware/auth')
const router =express.Router();

router.post('/signup',signup);
router.post('/login',login);
router.post('/course/create',createCourse);
router.get('/course',getCoursedetails);
router.post('/subject/create',createSubject);
router.post('/chapter/create',createChapter);
router.get('/chapter',getSubjectDetails);
router.post('/topic/create',createTopic);
router.post('/question/create',createQuestionWithImage);
router.get('/questions/test',getQuestionsForTest);
router.post('/test/create',createTest);
router.post('/chatBot',chatBot);
router.post('/completedtopic',updateProgress);
router.get('/getTotalTopics',getTotalTopics);
router.get('/users',getAllUsers);
router.get('/topics',getAllTopics);
router.post('/sendRequest',sendBattleRequest);
router.get('/progress',getProgress);
router.post('/removecompletetopic',removeFromComplete);
router.post('/questionPaper/create',generateQuestionPaper);
router.get('/getSyllabus',getSyllabus);
router.get('/userdata',getUserData);
router.get("/getCurrentSelectedChapters",getAllChapter);

module.exports=router;